### ISSUE TITLE
User/Authentication

### ISSUE THREAD

**Issue by vladtymo** [project-studying-dotnet/Streetcode-Server-June#180]
As a user, I would like to log in to the system so that I can get an access to some endpoints.

- [x] [Create JWT service](https://github.com/project-studying-dotnet/Streetcode-Server-June/issues/181)
- [x] [Create Login endpoint](https://github.com/project-studying-dotnet/Streetcode-Server-June/issues/182)
- [x] [Create Logout endpoint](https://github.com/project-studying-dotnet/Streetcode-Server-June/issues/183)
- [x] [Configure access restrictions based on user role](https://github.com/project-studying-dotnet/Streetcode-Server-June/issues/184)
